### ISSUE TITLE
no need for "wwwroot" folder in WebApi layer

### ISSUE THREAD

**Issue by duderdice** [matrixps/MariosPizzerias-SPA#5]
no need for "wwwroot" folder in WebApi layer, as the WebApi project does not host any web pages

**Comment by MrHydeout** [comment]
Got rid of wwwroot folder in WebApi layer. At this point it is but a distant memory.
See: commit 797aa9483c9a59a65a40a3b08eea597369d8f60f

**Comment by duderdice** [comment]
closed with pull request #6
